### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [Divkix/Alita_Robot#185]
## Traceback
The full traceback (if applicable).
[sheltered-ravine-64280-logs-1638092193792.txt](https://github.com/DivideProjects/Alita_Robot/files/7613163/sheltered-ravine-64280-logs-1638092193792.txt)

**Comment by annihilatorrrr** [comment]
Damn wtf

**Comment by annihilatorrrr** [comment]
https://github.com/DivideProjects/Alita_Robot/blob/d3380883a23ff3a6938830fa373365058a6d4bfe/alita/plugins/greetings.py#L307

**Comment by annihilatorrrr** [comment]
Fixed in beta , will merge soon.

**Comment by annihilatorrrr** [comment]
Thanks for opening the issue, this issue has been fixed in beta stage.

**Comment by ghost** [comment]
You are welcome and thanks for reply am also attaching another issues on another module its stats. Py it's also have errors.

2021-11-28 11:57:53,872 - [Alita_Robot] - ERROR - 'Filters' object has no attribute 'count_filter_aliases'
2021-11-28T11:57:53.874025+00:00 app[worker.1]: Traceback (most recent call last):
2021-11-28T11:57:53.874026+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
2021-11-28T11:57:53.874026+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2021-11-28T11:57:53.874027+00:00 app[worker.1]:   File "/app/alita/plugins/stats.py", line 61, in get_stats
2021-11-28T11:57:53.874028+00:00 app[worker.1]:     f"    <b>Aliases:</b> <code>{(fldb.count_filter_aliases())}</code>\n"
2021-11-28T11:57:53.874029+00:00 app[worker.1]: AttributeError: 'Filters' object has no attribute 'count_filter_aliases'

**Comment by annihilatorrrr** [comment]
Thanks for opening the issue, this issue has been fixed in beta stage.
The fix for this issue has been applied [here](https://github.com/DivideProjects/Alita_Robot/commit/b8cf7113bf50cadf5f3eb7ab7ff4475f9451f385)
