### ISSUE TITLE
disable.py

### ISSUE THREAD

**Issue by ubaynet** [Divkix/Alita_Robot#196]
When I Disable Command kickme or Other , It's Not Work. and then show errors like bellow.

```
2022-04-02T07:25:01.317224+00:00 app[worker.1]: Traceback (most recent call last):
2022-04-02T07:25:01.317225+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
2022-04-02T07:25:01.317226+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-04-02T07:25:01.317226+00:00 app[worker.1]:   File "/app/alita/plugins/disable.py", line 33, in disableit
2022-04-02T07:25:01.317226+00:00 app[worker.1]:     disable_list = db.get_disabled()
2022-04-02T07:25:01.317227+00:00 app[worker.1]:   File "/app/alita/database/disable_db.py", line 60, in get_disabled
2022-04-02T07:25:01.317227+00:00 app[worker.1]:     DISABLED_CMDS[self.chat_id]["commands"] = cmds
2022-04-02T07:25:01.317227+00:00 app[worker.1]: KeyError: -1001184552992
```

**Comment by annihilatorrrr** [comment]
Noted !
Fixed in local branch will be pushed soon !
